site_name: newthai docs & blog
site_url: https://geebee101.github.io/newthai/
repo_url: https://github.com/geebee101/newthai/

nav:
  - Home: index.md
#  - User Guide:
      # icon: material/book-open-page-variant
  - Getting started: usage.md
#    - Configuration: user-guide/configuration.md
  - Reference: reference.md
  - About: about.md
  - Blog: ### DO NOT add the individual posts
    - blog/index.md
    - Tags: blog/tags.md
  - Issue Tracker: 'https://github.com/geebee101/newthai/issues'


#theme: readthedocs
theme:
  name: material
  favicon: assets/arrows-down-to-people.svg
  logo: assets/arrows-down-to-people.svg
  language: en 
  icon:
    menu: material/abugida-thai
    repo: octicons/git-branch-16 # fontawesome/brands/github
  custom_dir: overrides
  palette:
    #scheme: default # Light theme by default
    # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: brown
      accent: deep orange
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode # system preference
        
  features:
    # - navigation.tabs
    #   When tabs are enabled, top-level sections are rendered in a menu layer below the header for large viewports
    # - navigation.tabs.sticky
    #   When sticky tabs are enabled, the tab bar remains visible at the top of the viewport when scrolling down the page
    - navigation.path #breadcrumb navigation
  #  - navigation.indexes
    - navigation.footer
  #   - toc.integrate # toc in the nav side panel
    - navigation.top # button back to top
    - search.suggest
    - search.highlight
  #   - content.tabs.link
  #   - content.code.annotate
  # icon:
  #   logo: material/library

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji: # this generates two errors in vscode, but works fine
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.caption

extra:
  # alternate:          ### doesn't work even with dir /th/index.md !!!
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: ภาษาไทย
  #     link: /th/
  #     lang: th
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social: ### not poss to add name
    # - icon: fontawesome/brands/bluesky 
    #   link: https://bluesky.social/@faillery
    - icon: fontawesome/brands/github
      link: https://github.com/geebee101/newthai/
    # - icon: fontawesome/brands/facebook
    #   link: https://facebook.com/newthai
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/r/learnthai/comments/1o3lzz0/textbooks_frequency_list_v2/ 
# built-in:
# Google Analytics – analytics (enabled by default)
# GitHub – github (enabled by default)
  analytics:
    provider: google
    property: G-JNZBS0ZKF8 # gprweb
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.extra:
  generator: false # remove "Generated by MkDocs" footer

copyright: >
  Copyright &copy; 2025 - แรช for newthai –
  <a href="#__consent">Change cookie settings</a>

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
  - tags
#  - typeset NOT INSTALLED

# extra_css:
#   - stylesheets/extra.css

# extra_javascript:
#   - javascripts/extra.js

### configure Giscus (Open Source, free), uses GitHub discussions as a backend.
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/
# you must be logged to github / alt: use r/leanrthai...


#.end